services:
  - type: web
    name: CustomerEntryForm1
    runtime: dotnet
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/DEMO.dll
    branch: main
    autoDeploy: true
